/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CustomerScreenRouteImport } from './routes/customer-screen'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as JoinRouteImport } from './routes/join'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin-users'
import { Route as ApiLinePushRouteImport } from './routes/api/line-push'
import { Route as ApiLineStatusRouteImport } from './routes/api/line-status'
import { Route as ApiSlipStatusRouteImport } from './routes/api/slip-status'
import { Route as ApiVerifySlipRouteImport } from './routes/api/verify-slip'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerScreenRoute = CustomerScreenRouteImport.update({
  id: '/customer-screen',
  path: '/customer-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin-users',
  path: '/api/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinePushRoute = ApiLinePushRouteImport.update({
  id: '/api/line-push',
  path: '/api/line-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLineStatusRoute = ApiLineStatusRouteImport.update({
  id: '/api/line-status',
  path: '/api/line-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlipStatusRoute = ApiSlipStatusRouteImport.update({
  id: '/api/slip-status',
  path: '/api/slip-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifySlipRoute = ApiVerifySlipRouteImport.update({
  id: '/api/verify-slip',
  path: '/api/verify-slip',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customer-screen': typeof CustomerScreenRoute
  '/display': typeof DisplayRoute
  '/join': typeof JoinRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/line-push': typeof ApiLinePushRoute
  '/api/line-status': typeof ApiLineStatusRoute
  '/api/slip-status': typeof ApiSlipStatusRoute
  '/api/verify-slip': typeof ApiVerifySlipRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customer-screen': typeof CustomerScreenRoute
  '/display': typeof DisplayRoute
  '/join': typeof JoinRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/line-push': typeof ApiLinePushRoute
  '/api/line-status': typeof ApiLineStatusRoute
  '/api/slip-status': typeof ApiSlipStatusRoute
  '/api/verify-slip': typeof ApiVerifySlipRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customer-screen': typeof CustomerScreenRoute
  '/display': typeof DisplayRoute
  '/join': typeof JoinRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/admin-users': typeof ApiAdminUsersRoute
  '/api/line-push': typeof ApiLinePushRoute
  '/api/line-status': typeof ApiLineStatusRoute
  '/api/slip-status': typeof ApiSlipStatusRoute
  '/api/verify-slip': typeof ApiVerifySlipRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/customer-screen'
    | '/display'
    | '/join'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/admin-users'
    | '/api/line-push'
    | '/api/line-status'
    | '/api/slip-status'
    | '/api/verify-slip'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/customer-screen'
    | '/display'
    | '/join'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/admin-users'
    | '/api/line-push'
    | '/api/line-status'
    | '/api/slip-status'
    | '/api/verify-slip'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/customer-screen'
    | '/display'
    | '/join'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/admin-users'
    | '/api/line-push'
    | '/api/line-status'
    | '/api/slip-status'
    | '/api/verify-slip'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CustomerScreenRoute: typeof CustomerScreenRoute
  DisplayRoute: typeof DisplayRoute
  JoinRoute: typeof JoinRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiLinePushRoute: typeof ApiLinePushRoute
  ApiLineStatusRoute: typeof ApiLineStatusRoute
  ApiSlipStatusRoute: typeof ApiSlipStatusRoute
  ApiVerifySlipRoute: typeof ApiVerifySlipRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-screen': {
      id: '/customer-screen'
      path: '/customer-screen'
      fullPath: '/customer-screen'
      preLoaderRoute: typeof CustomerScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-users': {
      id: '/api/admin-users'
      path: '/api/admin-users'
      fullPath: '/api/admin-users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/line-push': {
      id: '/api/line-push'
      path: '/api/line-push'
      fullPath: '/api/line-push'
      preLoaderRoute: typeof ApiLinePushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/line-status': {
      id: '/api/line-status'
      path: '/api/line-status'
      fullPath: '/api/line-status'
      preLoaderRoute: typeof ApiLineStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slip-status': {
      id: '/api/slip-status'
      path: '/api/slip-status'
      fullPath: '/api/slip-status'
      preLoaderRoute: typeof ApiSlipStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-slip': {
      id: '/api/verify-slip'
      path: '/api/verify-slip'
      fullPath: '/api/verify-slip'
      preLoaderRoute: typeof ApiVerifySlipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CustomerScreenRoute: CustomerScreenRoute,
  DisplayRoute: DisplayRoute,
  JoinRoute: JoinRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiLinePushRoute: ApiLinePushRoute,
  ApiLineStatusRoute: ApiLineStatusRoute,
  ApiSlipStatusRoute: ApiSlipStatusRoute,
  ApiVerifySlipRoute: ApiVerifySlipRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
